name: Publish Docker images and release artifacts

on:
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mjmbischoff/esql-check
  ES_RELEASE_TAG: v${{ github.event.release.tag_name }}

jobs:
  check-latest:
    name: Check if release is latest
    runs-on: ubuntu-latest
    outputs:
      is_latest: ${{ steps.check.outputs.is_latest }}
    steps:
      - name: Determine if this is the latest release
        id: check
        run: |
          releases=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases)

          latest_tag=$(echo "$releases" | jq -r '[.[] | select(.draft==false) | select(.prerelease==false)][0].tag_name')

          echo "Latest release tag: $latest_tag"
          echo "Current release tag: ${{ github.event.release.tag_name }}"

          if [[ "${{ github.event.release.tag_name }}" == "$latest_tag" ]]; then
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    needs: check-latest
    name: Build Docker Images & Release Artifacts (${{ matrix.lang }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [java, python, go]

    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: tags
        run: |
          TAGS="${{ env.IMAGE_NAME }}:${{ matrix.lang }}-${{ github.event.release.tag_name }}"
          if [ "${{ matrix.lang }}" = "java" ] && [ "${{ needs.check-latest.outputs.is_latest }}" = "true" ]; then
            TAGS="$TAGS,${{ env.IMAGE_NAME }}:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.lang }}
          file: ./${{ matrix.lang }}/Dockerfile
          push: true
          build-args: |
            GIT_REF=${{ env.ES_RELEASE_TAG }}
          tags: ${{ steps.tags.outputs.tags }}

      - name: Prepare dist directory
        run: mkdir -p dist

      - name: Extract artifacts
        run: |
          mkdir -p build

          if [ "${{ matrix.lang }}" = "java" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/java.tar \
              ./java

            tar -C ./dist --strip-components=1 -xf ./build/java.tar export/
            mv ./dist/esql-check ./dist/esql-check-java

          elif [ "${{ matrix.lang }}" = "python" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/python.tar \
              ./python

            tar -C ./dist --strip-components=1 -xf ./build/python.tar export/
            cd dist && \
              zip -r parser-python.zip python-grammar && \
              rm -rf python-grammar && \
              cd ..

          elif [ "${{ matrix.lang }}" = "go" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/go.tar \
              ./go

            tar -C ./dist --strip-components=1 -xf ./build/go.tar export/
            mv ./dist/esql-check ./dist/esql-check-go
            cd dist && \
              zip -r parser-go.zip go-grammar && \
              rm -rf go-grammar && \
              cd ..
          fi

      - name: Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: Import GPG key
        if: matrix.lang == 'java'
        run: |


      - name: Prepare Maven Central upload bundle
        if: matrix.lang == 'java'
        run: |
          VERSION=${{ github.event.release.tag_name }}
          BUNDLE_DIR="$GITHUB_WORKSPACE/upload/dev/bischoff/michael/elastic/esql/parser/$VERSION"
          DIST_DIR="$GITHUB_WORKSPACE/dist"

          mkdir -p "$BUNDLE_DIR"

          cp "$DIST_DIR/generated-antlr-esql-parser.jar"          "$BUNDLE_DIR/parser-${VERSION}.jar"
          cp "$DIST_DIR/generated-antlr-esql-parser-sources.jar"  "$BUNDLE_DIR/parser-${VERSION}-sources.jar"
          cp "$DIST_DIR/generated-antlr-esql-parser-javadoc.jar"  "$BUNDLE_DIR/parser-${VERSION}-javadoc.jar"

          sed "s|<version>0.0.0</version>|<version>${VERSION}</version>|" \
          "$GITHUB_WORKSPACE/.github/workflows/dist-pom.xml"    > "$BUNDLE_DIR/parser-${VERSION}.pom"

          # Generate SHA1 and MD5 checksums for all files
          for file in "$BUNDLE_DIR"/*; do
              sha1sum "$file" | awk '{print $1}' > "$file.sha1"
              md5sum "$file" | awk '{print $1}' > "$file.md5"
          done

          # Import GPG key
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys

          # Sign artifacts with GPG
          for file in "$BUNDLE_DIR"/*.{jar,pom}; do
              gpg --batch --yes \
                  --pinentry-mode loopback \
                  --passphrase "${{ secrets.GPG_PASSPHRASE }}" \
                  --detach-sign --armor "$file"
          done

          # Package everything into central-bundle.zip
          cd "$GITHUB_WORKSPACE/upload"
          zip -r "$GITHUB_WORKSPACE/central-bundle.zip" .

      - name: Upload to Maven Central (via new API)
        if: matrix.lang == 'java'
        run: |
          TOKEN=$(printf "%s:%s" "${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}" \
                              "${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}" | base64)
      
          curl -v \
            --verbose \
            -H "Authorization: Bearer $TOKEN" \
            --form bundle=@central-bundle.zip \
            https://central.sonatype.com/api/v1/publisher/upload?name=esql-parser&publishingType=AUTOMATIC