name: Publish Docker images and release artifacts

on:
  release:
    types: [published]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mjmbischoff/esql-check
  ES_RELEASE_TAG: v${{ github.event.release.tag_name }}

jobs:
  build-and-publish:
    name: Build Docker Images & Release Artifacts (${{ matrix.lang }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [java, python, go]

    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: tags
        run: |
          TAGS="${{ env.IMAGE_NAME }}:${{ matrix.lang }}-${{ github.event.release.tag_name }}"
          if [ "${{ matrix.lang }}" = "java" ]; then
            TAGS="$TAGS,${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }},${{ env.IMAGE_NAME }}:latest"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.lang }}
          file: ./${{ matrix.lang }}/Dockerfile
          push: true
          build-args: |
            GIT_REF=${{ env.ES_RELEASE_TAG }}
          tags: ${{ steps.tags.outputs.tags }}

      - name: Prepare dist directory
        run: mkdir -p dist

      - name: Extract artifacts
        run: |
          mkdir -p build

          if [ "${{ matrix.lang }}" = "java" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/java.tar \
              ./java

            tar -C ./dist --strip-components=1 -xf ./build/java.tar export/
            mv ./dist/esql-check ./dist/esql-check-java

          elif [ "${{ matrix.lang }}" = "python" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/python.tar \
              ./python

            tar -C ./dist --strip-components=1 -xf ./build/python.tar export/
            cd dist && \
              zip -r parser-python.zip python-grammar && \
              rm -rf python-grammar && \
              cd ..

          elif [ "${{ matrix.lang }}" = "go" ]; then
            docker buildx build \
              --build-arg GIT_REF=${{ env.ES_RELEASE_TAG }} \
              --target export \
              --output type=tar,dest=./build/go.tar \
              ./go

            tar -C ./dist --strip-components=1 -xf ./build/go.tar export/
            mv ./dist/esql-check ./dist/esql-check-go
            cd dist && \
              zip -r parser-go.zip go-grammar && \
              rm -rf go-grammar && \
              cd ..
          fi

      - name: Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

